sonar.projectKey=sae-dev
sonar.projectName=SAE Dev
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

sonar.sources=\
  backend/ressources_enseignements/src/main/java,\
  frontend/ressources_enseignements/src

sonar.tests=backend/ressources_enseignements/src/test/java

sonar.java.source=21
sonar.java.binaries=backend/ressources_enseignements/target/classes
sonar.java.test.binaries=backend/ressources_enseignements/target/test-classes

# JaCoCo (backend Java)
sonar.coverage.jacoco.xmlReportPaths=\
  backend/ressources_enseignements/target/site/jacoco/jacoco.xml

# LCOV (frontend Angular)
sonar.javascript.lcov.reportPaths=\
  frontend/ressources_enseignements/coverage/ressources_enseignement/lcov.info
sonar.typescript.lcov.reportPaths=\
  frontend/ressources_enseignements/coverage/ressources_enseignement/lcov.info

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/target/**,\
  **/*.min.js,\
  frontend/ressources_enseignements/src/environments/**,\
  frontend/ressources_enseignements/src/main.ts,\
  frontend/ressources_enseignements/src/main.server.ts

sonar.coverage.exclusions=\
  **/*.spec.ts,\
  **/app.config.ts,\
  **/main.ts,\
  **/main.server.ts,\
  **/*environment*,\
  **/ProjectApplicationTests.java
