# Clé unique du projet SonarQube
sonar.projectKey=sae-dev

# Nom affiché dans SonarQube
sonar.projectName=SAE Dev

# Version du projet
sonar.projectVersion=1.0

# Attendre la Quality Gate avant de terminer l'analyse
sonar.qualitygate.wait=true

# Encodage des fichiers source
sonar.sourceEncoding=UTF-8

# Dossiers contenant le code source (frontend + backend)
sonar.sources=frontend/ressources_enseignements/src,backend/ressources_enseignements/src/main/java/sae/project

# Dossier des tests (facultatif si tu n'as pas de tests)
# sonar.tests=...

# Dossier des fichiers compilés Java (facultatif mais recommandé pour certaines règles)
# sonar.java.binaries=backend/ressources_enseignements/target/classes
