app.cors.allowed-origins=http://localhost:4200/

spring.datasource.url=jdbc:postgresql://localhost:5432/ressources_enseignements
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql

logging.level.org.springframework.jdbc=DEBUG
spring.jpa.show-sql=true
