spring.application.name=project

#driver de la bdd
spring.datasource.driver-class-name=org.apache.derby.client.ClientAutoloadedDriver
#spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver

#url de la bdd
spring.datasource.url=jdbc:derby://localhost:1527/sample
#identifiants bdd
spring.datasource.username=app
spring.datasource.password=app
#dialecte de BDD utilisé par l'ORM
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyDialect
spring.jpa.hibernate.ddl-auto=none
#positionnement du niveau de log à DEBUG (INFO par défaut) pour tomcat et Spring JDBC
debug=true
logging.level.org.springframework.jdbc=DEBUG